### PR TITLE
Issue #2856282 by Elendev: Add implementation of transformDimensions into CropEffect

### PR DESCRIPTION
**Pull request by Elendev**
Add support of transformDimensions to be able to use the imageStyle's `transformDimensions` method.

To avoid duplication of code, I've made a small refactoring of getCrop to use the new getCropFromUri method.

### CODE REVIEW

**Comment by slashrsm** [comment]
Please open an issue in https://www.drupal.org/project/issues/crop and cross-link this PR.

**Comment by Elendev** [comment]
Done !

**Comment by woprrr** [comment]
This subject already exist on : #2778239 and the situation are blocked by Tests

**Comment by woprrr** [comment]
Already merged in newer 1.1 release.

**Pull request closed without merging**
